### ISSUE TITLE
[SOLVED] Font file cannot be found in Visual Code

### ISSUE THREAD

**Issue by tadam98** [gnikkoch96/Python-Pomodoro-Timer-GUI#2]
Hi,

There is a problem with the fonts. I have Installed the fonts into windows and still get the error below.
**Correction** add the  `"cwd": "${fileDirname}"`, in the **launch.json** of visual code. And it works !!
```
"configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "cwd": "${fileDirname}",
            "stopOnEntry": true
        }

```
Exception: Error: [1000] Message:       Font file could not be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...Python-Pomodoro-Timer-GUI-master\main.py", line 59, in <module>
    create_windows()
  File "c:\Download\medium\Examples\2021-10-21-Python-package-builds-awesome-GUI\Python-Pomodoro-Timer-GUI-master\main.py", line 18, in create_windows
    create_dpg_fonts()
  File "c:\Download\medium\Examples\2021-10-21-Python-package-builds-awesome-GUI\Python-Pomodoro-Timer-GUI-master\main.py", line 33, in create_dpg_fonts
    dpg.add_font("resources/fonts/**Simpleton-Gothic.ttf**", 20, tag=DEFAULT_FONT_TAG)
  File "C:\Users\Mickey\Miniconda3\envs\medium\lib\site-packages\dearpygui\dearpygui.py", line 4128, in add_font
    return internal_dpg.add_font(file, size, label=label, user_data=user_data, use_internal_label=use_internal_label, tag=tag, parent=parent, **kwargs)
SystemError: <built-in function add_font> returned a result with an error set
![Screenshot](https://user-images.githubusercontent.com/21152079/139796262-33dd98e2-c106-404d-8288-e623d203051f.jpg)

**Comment by gnikkoch96** [comment]
That's good to hear! 😃. I'm going to close this issue now. Thanks for trying out my program 👍
